# Generated by Django 4.2.11 on 2025-05-20 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Bangladeshi number (e.g., +8801775289775, 01775289775, or 1775289775).', regex='^\\+?880\\d{10}$|^0\\d{10}$|^\\d{10}$')]),
        ),
        migrations.AddConstraint(
            model_name='employer',
            constraint=models.UniqueConstraint(fields=('user', 'email'), name='unique_user_email'),
        ),
    ]
