# Generated by Django 4.2.11 on 2025-05-20 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_alter_employer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be 11 digits starting with '0' (e.g., 01775289775).", regex='^0\\d{10}$'), django.core.validators.RegexValidator(message='Phone number must start with a valid Bangladeshi mobile prefix (013, 014, 015, 016, 017, 018, 019).', regex='^0(13|14|15|16|17|18|19)\\d{8}$')]),
        ),
    ]
