version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=${SECRET_KEY:-django-insecure-kwtw-n3x^ehmpxxpykxoh**gj)v1c+xvoj=9r2us7&gd&djudo}
      - DATABASE_URL=sqlite:////app/db.sqlite3
    command: python manage.py runserver 0.0.0.0:8000